/* ————————————————————————————————————————
   A profile summary written without the model.

   The onboarding summary is generated by Claude. When that call fails —
   no API key, a rate limit, a network blip — the screen previously sat on
   "Putting this into words…" forever, because a null summary and a
   still-loading summary render identically.

   This is the floor: a plain, accurate paragraph composed from the answers
   the person just gave. It is not as warm as the model's version, and it
   doesn't pretend to be. It is always available, costs nothing, and means
   the last step of onboarding can never be a dead end.
   ———————————————————————————————————————— */

import type { Profile, StudentValue } from "@/lib/types";

const VALUE_WORDS: Record<StudentValue, string> = {
  "research-access": "research opportunities",
  "greek-life": "Greek life",
  "d1-sports": "Division I sports",
  "lgbtq-friendly": "an LGBTQ+-friendly campus",
  "religious-affiliation": "a religious community",
  "political-climate": "a political climate you fit into",
  diversity: "a diverse student body",
  "study-abroad": "study abroad",
  "co-op-internships": "co-ops and internships",
  "mental-health-support": "strong mental-health support",
};

const REGION_WORDS: Record<string, string> = {
  northeast: "the Northeast",
  "mid-atlantic": "the Mid-Atlantic",
  south: "the South",
  midwest: "the Midwest",
  southwest: "the Southwest",
  west: "the West",
  northwest: "the Northwest",
};

/** "a, b, and c" — with the serial comma, and no dangling "and". */
function list(items: string[]): string {
  const clean = items.filter(Boolean);
  if (clean.length === 0) return "";
  if (clean.length === 1) return clean[0]!;
  if (clean.length === 2) return `${clean[0]} and ${clean[1]}`;
  return `${clean.slice(0, -1).join(", ")}, and ${clean.at(-1)}`;
}

const money = (n: number) => `$${Math.round(n / 1000)}k`;

export function localSummary(profile: Profile): string {
  if (profile.role === "parent") {
    const parts: string[] = [];
    parts.push(
      `You're a ${profile.relationship || "parent"} helping a ${profile.studentGrade}th grader think about college.`,
    );
    if (profile.priorities?.length) {
      parts.push(`What matters most to you: ${list(profile.priorities).toLowerCase()}.`);
    }
    if (profile.budgetPerYear) {
      parts.push(
        `You're working with a budget around ${money(profile.budgetPerYear)} a year — we'll show net price, not sticker price, so that number means something.`,
      );
    }
    if (profile.biggestWorry?.trim()) {
      parts.push(`The thing on your mind: ${profile.biggestWorry.trim()}`);
    }
    const involvement =
      profile.involvementLevel === "hands-on"
        ? "closely involved"
        : profile.involvementLevel === "light-touch"
          ? "available without hovering"
          : "checking in regularly";
    parts.push(`You'd like to be ${involvement} through the process.`);
    return parts.join(" ");
  }

  const parts: string[] = [];
  const name = profile.firstName && profile.firstName !== "there" ? profile.firstName : null;

  parts.push(
    `${name ? `${name}, you're` : "You're"} in ${profile.gradeLevel}th grade${
      profile.undecided
        ? " and still figuring out what you want to study — which is a completely reasonable place to be"
        : profile.intendedMajors?.length
          ? `, looking at ${list(profile.intendedMajors)}`
          : ""
    }.`,
  );

  const academics: string[] = [];
  if (profile.gpa?.unweighted) academics.push(`a ${profile.gpa.unweighted} unweighted GPA`);
  else if (profile.gpa?.weighted) academics.push(`a ${profile.gpa.weighted} weighted GPA`);
  const rigor = (profile.rigor?.apCount ?? 0) + (profile.rigor?.honorsCount ?? 0);
  if (rigor > 0) {
    academics.push(
      `${rigor} advanced ${rigor === 1 ? "course" : "courses"} between AP and honors`,
    );
  }
  if (profile.testScores?.sat) academics.push(`an SAT of ${profile.testScores.sat}`);
  if (profile.testScores?.act) academics.push(`an ACT of ${profile.testScores.act}`);
  if (academics.length) parts.push(`Academically you're bringing ${list(academics)}.`);
  else if (profile.testScores?.planningToTest) {
    parts.push("You haven't tested yet, which leaves the test-optional door wide open.");
  }

  const prefs: string[] = [];
  if (profile.geography?.regions?.length) {
    prefs.push(
      `${list(profile.geography.regions.map((r) => REGION_WORDS[r] ?? r))}`,
    );
  }
  if (profile.campus?.settings?.length) {
    prefs.push(`${list(profile.campus.settings.map((s) => `${s.replace("-", " ")} campuses`))}`);
  }
  if (prefs.length) parts.push(`You're drawn to ${list(prefs)}.`);

  if (profile.values?.length) {
    parts.push(
      `In a community, you care about ${list(profile.values.map((v) => VALUE_WORDS[v] ?? v))}.`,
    );
  }

  if (profile.budget?.maxPerYear) {
    parts.push(
      `Cost matters: you're aiming under about ${money(profile.budget.maxPerYear)} a year. We'll always show you net price — what a family like yours actually pays — rather than the sticker number.`,
    );
  }

  parts.push(
    "That's enough to start building a realistic list. You can change any of this later.",
  );

  return parts.join(" ");
}
